name: dhydro_to_isg_new_hl
channels:
  - conda-forge
  - default
dependencies:
  - python<3.12
  - pip
  - netCDF4
  - tqdm
  - matplotlib
  - numpy
  - scipy
  - pandas
  - shapely
  - sympy
  - geopandas>=0.10
  - xarray
  - jupyter
  - plotly
  - pydantic=1.10
  - pip:
      - hydrolib-core==0.5.2
      - delft3dfmpy==1.2.2
      - kaleido